version: '2'

services:
        redis:
                image: redis:alpine
                volumes:
                        - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
                        - ./.redisbackup:/redisbackup/:rw
                expose:
                        - "6397"
                network_mode: "bridge"
        nsproxy:
                #build: ./nsproxy
                image: unixvoid/nsproxy
                depends_on:
                        - redis
                volumes:
                        - ../nsproxy/config.gcfg:/config.gcfg:ro
                expose:
                        - "8080"
                network_mode: "bridge"
                links:
                        - redis
